version: '3.6'
services:
  event_service:
    command: ["yarn", "run", "start:debug"]
    volumes:
      - ./event_service:/usr/src/app/event_service
      # hack to prevent mounting node_modules
      - /usr/src/app/event_service/node_modules/
  event_processor:
    # -L runs nodemon in legacy mode (necessary over Docker)
    command: sh -c "chmod +x entrypoint.sh && ./node_modules/nodemon/bin/nodemon.js -L --exec ./entrypoint.sh"
    environment:
      - DEBUG=${EVENT_PROCESSOR_DEBUG}
      - VERBOSE_OUTPUT=${VERBOSE_OUTPUT}
      - RUN_SCHEDULER=${RUN_SCHEDULER}
      - SCHEDULE_INTERVAL=5
      - SPIDER_NAME=${SPIDER_NAME}
    volumes:
      - ./event_processor:/usr/src/app/event_processor
      - /usr/src/app/event_processor/node_modules/
      - event_processor_data:/usr/src/app/event_processor/data/
      - event_processor_lock:/usr/src/app/event_processor/lock/
      - event_processor_scrapy:/usr/src/app/event_processor/.scrapy/
  in2it_site:
    command: ["yarn", "run", "docker-debug"]
    volumes:
      - ./in2it_site:/usr/src/app/in2it_site
      - /usr/src/app/in2it_site/node_modules/
    environment:
      - IN2IT_API_URL=${IN2IT_API_URL:-api.localhost}
  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    command: sh -c "chmod +x entrypoint.sh && nodemon -L --exec ./entrypoint.sh"
    environment:
      - SERVER_NAME=localhost
  ndscheduler:
    command: "./node_modules/nodemon/bin/nodemon.js -L -u simple_scheduler/scheduler.py"
    volumes:
      - ../ndscheduler:/usr/src/app/ndscheduler
      - ndscheduler_modules:/usr/src/app/ndscheduler/node_modules/
    environment:
      - DEBUG=${SCHEDULER_DEBUG}
volumes:
  ndscheduler_modules:
  postgres_data:
  event_processor_data:
  event_processor_lock:
  event_processor_scrapy: